export const emptyFAQdata = {
    americanGrades: {
        sportMan: [
            { question: 'How many people have climbed 5.15d?', answer: '' },
            { question: 'How many people have climbed 5.15c?', answer: '' },
            { question: 'How many 5.15d sport climbing routes are there?', answer: '' },
            { question: 'How many 5.15c sport climbing routes are there?', answer: '' },
            { question: 'Who is the strongest male sport climber?', answer: '' },
            { question: 'Who was the first to climb 5.15c sport climb?', answer: '' },
            { question: 'Who was the first to climb 5.15d sport climb?', answer: '' },
            { question: "What's the most recent male 5.15c in sport climbing?", answer: '' },
            { question: "What's the most recent male 5.15d in sport climbing?", answer: '' }
        ],
        sportWoman: [
            { question: 'How many woman have climbed 5.15b?', answer: '' },
            { question: 'How many woman have climbed 5.15a?', answer: '' },
            { question: 'Who is the strongest female sport climber?', answer: '' },
            { question: 'Who was the first woman to climb 5.15a sport climb?', answer: '' },
            { question: 'Who was the first woman to climb 5.15b sport climb?', answer: '' },
            { question: 'Who was the first woman to climb 5.15c sport climb?', answer: '' },
            { question: "What's the most recent female 5.15a in sport climbing?", answer: '' },
            { question: "What's the most recent female 5.15b in sport climbing?", answer: '' },
        ],
        boulderMan: [
            { question: 'How many people have climbed V16?', answer: '' },
            { question: 'How many people have climbed V17?', answer: '' },
            { question: 'How many V16 boulders are there?', answer: '' },
            { question: 'How many V17 boulders are there?', answer: '' },
            { question: 'Who is the strongest male boulder climber?', answer: '' },
            { question: 'Who was the first to climb V16 boulder?', answer: '' },
            { question: 'Who was the first to climb V17 boulder?', answer: '' },
            { question: "What's the most recent male V16 in bouldering?", answer: '' },
            { question: "What's the most recent male V17 in bouldering?", answer: '' },
        ],
        boulderWoman: [
            { question: 'How many woman have climbed V14?', answer: '' },
            { question: 'How many woman have climbed V15?', answer: '' },
            { question: 'Who is the strongest female boulder climber?', answer: '' },
            { question: 'Who was the first woman to climb V14 boulder?', answer: '' },
            { question: 'Who was the first woman to climb V15 boulder?', answer: '' },
            { question: 'Who was the first woman to climb V16 boulder?', answer: '' },
            { question: "What's the most recent female V14 in bouldering?", answer: '' },
            { question: "What's the most recent female V15 in bouldering?", answer: '' },
        ],
    },
    europeanGrades: {
        sportMan: [
            { question: 'How many people have climbed 9c?', answer: '' },
            { question: 'How many people have climbed 9b+?', answer: '' },
            { question: 'How many 9c sport climbing routes are there?', answer: '' },
            { question: 'How many 9b+ sport climbing routes are there?', answer: '' },
            { question: 'Who is the strongest male sport climber?', answer: '' },
            { question: 'Who was the first to climb 9b+ sport climb?', answer: '' },
            { question: 'Who was the first to climb 9c sport climb?', answer: '' },
            { question: "What's the most recent male 9b+ in sport climbing?", answer: '' },
            { question: "What's the most recent male 9c in sport climbing?", answer: '' }
        ],
        sportWoman: [
            { question: 'How many woman have climbed 9b?', answer: '' },
            { question: 'How many woman have climbed 9a+?', answer: '' },
            { question: 'Who is the strongest female sport climber?', answer: '' },
            { question: 'Who was the first woman to climb 9a+ sport climb?', answer: '' },
            { question: 'Who was the first woman to climb 9b sport climb?', answer: '' },
            { question: 'Who was the first woman to climb 9b+ sport climb?', answer: '' },
            { question: "What's the most recent female 9a+ in sport climbing?", answer: '' },
            { question: "What's the most recent female 9b in sport climbing?", answer: '' },
        ],
        boulderMan: [
            { question: 'How many people have climbed 8C+?', answer: '' },
            { question: 'How many people have climbed 9A?', answer: '' },
            { question: 'How many 8C+ boulders are there?', answer: '' },
            { question: 'How many 9A boulders are there?', answer: '' },
            { question: 'Who is the strongest male boulder climber?', answer: '' },
            { question: 'Who was the first to climb 8C+ boulder?', answer: '' },
            { question: 'Who was the first to climb 9A boulder?', answer: '' },
            { question: "What's the most recent male 8C+ in bouldering?", answer: '' },
            { question: "What's the most recent male 9A in bouldering?", answer: '' },
        ],
        boulderWoman: [
            { question: 'How many woman have climbed 8B+?', answer: '' },
            { question: 'How many woman have climbed 8C?', answer: '' },
            { question: 'Who is the strongest female boulder climber?', answer: '' },
            { question: 'Who was the first woman to climb 8B+ boulder?', answer: '' },
            { question: 'Who was the first woman to climb 8C boulder?', answer: '' },
            { question: 'Who was the first woman to climb 8C+ boulder?', answer: '' },
            { question: "What's the most recent female 8B+ in bouldering?", answer: '' },
            { question: "What's the most recent female 8C in bouldering?", answer: '' }
        ],
    }
};
